# Generated by Django 3.2.19 on 2023-07-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Landing',
            new_name='Banner',
        ),
    ]
