# Generated by Django 3.2.19 on 2023-07-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_destricts_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destricts',
            new_name='Districts',
        ),
    ]
