# Generated by Django 3.2.19 on 2023-07-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_destricts_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='district_images'),
        ),
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='state_images'),
        ),
        migrations.CreateModel(
            name='Treks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='treks_images')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.districts')),
            ],
        ),
    ]
