# Generated by Django 3.2.19 on 2023-07-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20230718_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='districts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='state',
            name='image',
        ),
        migrations.RemoveField(
            model_name='treks',
            name='title',
        ),
        migrations.AddField(
            model_name='districts',
            name='d_images',
            field=models.ManyToManyField(to='frontend.Images'),
        ),
        migrations.AddField(
            model_name='state',
            name='s_images',
            field=models.ManyToManyField(to='frontend.Images'),
        ),
        migrations.AddField(
            model_name='treks',
            name='t_title',
            field=models.ManyToManyField(to='frontend.Images'),
        ),
    ]
