# Generated by Django 3.2.19 on 2023-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20230718_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.RemoveField(
            model_name='treks',
            name='t_title',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='treks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='treks',
            name='image',
        ),
        migrations.AddField(
            model_name='treks',
            name='image',
            field=models.ManyToManyField(to='frontend.Images'),
        ),
    ]
