# Generated by Django 3.2.19 on 2023-07-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20230718_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treks',
            old_name='image',
            new_name='t_image',
        ),
    ]
