# Generated by Django 3.2.19 on 2023-07-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_rename_image_treks_t_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treks',
            name='t_image',
        ),
    ]
