# Generated by Django 3.2.19 on 2023-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_remove_treks_t_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treks',
            name='t_image',
            field=models.ManyToManyField(to='frontend.Images'),
        ),
    ]
