# Generated by Django 3.2.19 on 2023-07-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_treks_t_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='d_images',
        ),
        migrations.RemoveField(
            model_name='state',
            name='s_images',
        ),
        migrations.AddField(
            model_name='districts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='district/'),
        ),
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='state/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
