# Generated by Django 3.2.19 on 2023-08-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20230719_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iternary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='treks',
            name='altitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treks',
            name='difficulty_level',
            field=models.PositiveIntegerField(blank=True, choices=[('1', 'Easy'), ('2', 'Moderate'), ('3', 'Difficult')], null=True),
        ),
        migrations.AddField(
            model_name='treks',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treks',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treks',
            name='trek_length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treks',
            name='Iternary',
            field=models.ManyToManyField(to='frontend.Iternary'),
        ),
    ]
