# Generated by Django 3.2.19 on 2023-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20230815_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='treks',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
