# Generated by Django 3.2.19 on 2023-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20230820_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
