# Generated by Django 3.2.19 on 2023-08-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20230820_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='treks',
            name='guidance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treks',
            name='quick_facts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
